### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by lyfe00011**

### CODE REVIEW

**Comment by phaticusthiccy** [comment]
Thanks for helping 😊

**Comment by Nargisnjani** [comment]
eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUJFYmZmSEcwRUpxd3Y3Zk9mZjJYU3M3bmVtV09RZmpqeFVTK1FKYUoxOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVVR3WFoyVzZMQkVLM2FxaElRVG42bGYvSmFyUytwVFFUMHBlay9ORHdqTT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLR3h6YXcxM1FNVjFmMlprM3pKYk1KcVRjdEwrSzNiYXR0VDZiVmFtdFdjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLZGFVUkV3djNQUUFBdExtVnlaN0Yrc3g5R1ZzUlRIZDFOZ3ZIN0s3dkdvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVOSHhteW9VVkh6Y2tOSC9nS1FmK1RrU2tpbnpEZkc1SlRKTjVVOFh4WG89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjcyNmszOWY3RmF1RUpTcDFZVkNQZi9reGh1U3BZeTZDYk4xTW50U1ZEaWs9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0N2aE1LZDhaUDVuOWJOOW96NmVaQ3FFZjJqV1BzUDJmY21JUUJqUUIzYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZFFDSkloWnE3QXlqcHM1Y0hWUE5VNytJeWMxSzQ3SzhrRmZVcVlobmQwRT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlZaRmdrQ1ovdmxWVlo3bVBVY0NoR0ZvRGZYOUowYm9OUmI1dWUzZXFLZmdsRGNCaDBMN1FSNDIwYmIyRTVEUEs4ZnZDbXhqZkxScjYxNFFYczRjbGlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQ4LCJhZHZTZWNyZXRLZXkiOiJiSGprWHJHLzZvS0RpWFU5d3JFWFRQVjMvL3RkeEtYWGU3WUdzaW1JNjlVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjkyMzAyNTA4NDI2N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI0NDlBQ0E3ODgwRjg3MTk5Mjg0QjQyOUIyRDhGNkMxMiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIzODc5MzMyfSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MjMwMjUwODQyNjdAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNTkzMzExQUUxMkJCQzhFNTNBQkVCNDMxRTA3MEQ1RDgifSwibWVzc2FnZVRpbWVzdGFtcCI6MTcyMzg3OTMzMn0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzMDI1MDg0MjY3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjQwMzQ4QkFBMDgzN0UwRjkyQjBGQjU3RDQzM0U1MzY3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MjM4NzkzMzN9LHsia2V5Ijp7InJlbW90ZUppZCI6IjkyMzAyNTA4NDI2N0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIwQkREN0NCRDMzOTEyOUMzQjM4MTM4Mzg4MUVGRTkwMiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzIzODc5MzM0fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJuOTRmTDE2SlFObTFwNkI3RldnZDd3IiwicGhvbmVJZCI6IjUwNDhhYmEyLTA4MTktNGE0NC1iMmZiLWQ3NmZkMmQwNWY1NyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJRd0pVL29OMVVVLytIY1lSS3FxWFJwSDhhMVk9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidjJGRytDc1pBMktiN2hZSlZZNWJXZ2ZDeU13PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IjJSQTdTRUpSIiwibWUiOnsiaWQiOiI5MjMwMjUwODQyNjc6MUBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJCcm9rZW4ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0pYOTNaMEZFSldmZ2JZR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Imk5VHdGQXVRY3JDcFRnWW1ZMldjalRxZ2JOY3M4SUZ1M2dJeHdYRk51R0k9IiwiYWNjb3VudFNpZ25hdHVyZSI6ImxWUHRtZGVDNnBEeE5PcmtSeUM2Y1liY0hhSzNwejZXVnRUTEpiWkJoTG1NQVVzeE9KYVlYS1YxSVlTVjQ4aWlnb2gzNTVGNUtZYWxteE5uZEE4Q0RnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJpRWFDeE10RTFpZlFGSmhxdXRscDhsck9sVDNjMVZlbHViaEpNMlN4RmpDUi9FbXBqMmdpMkZzS3pscDQzQjU4dzg2OERyUkVLNjdqSUZtMEhHTmppdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjkyMzAyNTA4NDI2NzoxQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQll2VThCUUxrSEt3cVU0R0ptTmxuSTA2b0d6WExQQ0JidDRDTWNGeFRiaGkifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjM4NzkzMzAsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRlBZIn0=

**Comment by Nargisnjani** [comment]
Nargisnjani

**Comment by Nargisnjani** [comment]
https://github.com/phaticusthiccy/WhatsAsenaDuplicated/pull/10

**Comment by Nargisnjani** [comment]
WhatsApp bot

**Pull request merged**
