### PR TITLE
Delete EN.json

### PR DESCRIPTION
**Pull request by Shenstudio-max**
Gsnsusvsksuejdndixndvdhdmsgdkeksjfnk8isieveuele

### CODE REVIEW

**Comment by Shenstudio-max** [comment]
Bsvsgehejeje

**Comment by Shenstudio-max** [comment]
Yshshshe

**Comment by Shenstudio-max** [comment]
`**hshsjwjwjuejejej**`

**Comment by phaticusthiccy** [comment]
Unacceptable Pull Request.

**Pull request closed without merging**
