### PR TITLE
Fixed 🛠️ [ Critical Error ] ✅️

### PR DESCRIPTION
**Pull request by TOXIC-DEVIL**
Fixed Critical Error ✅️ @phaticusthiccy 

@phaticusthiccy Also, Baran can you fix eva fulleva.. Its not working 😟.. i will help you like this fixing some minor & critical errors/bugs 🥰 @phaticusthiccy

### CODE REVIEW

**Comment by souravkl11** [comment]
@TOXIC-DEVIL  Nee oru killadi thanne

**Comment by TOXIC-DEVIL** [comment]
> @TOXIC-DEVIL Nee oru killadi thanne

Entha mwonu angane oru talk 😂 ni killadi alle 😂

**Review by phaticusthiccy — APPROVED** [review]
An overlooked space. Thanks.

**Comment by TOXIC-DEVIL** [comment]
> An overlooked space. Thanks.

Welcome 💕

**Pull request merged**
