### PR TITLE
Create insta.js

### PR DESCRIPTION
**Pull request by Oreki-san**
gives you information about instagram account

### CODE REVIEW

**Comment by phaticusthiccy** [comment]
WhatsAsena don't use, REST API. Please make a NPM module for that.

**Comment by Oreki-san** [comment]
> WhatsAsena don't use, REST API. Please make a NPM module for that.

why tho...with use of rest api there are alot of features can be added in the bot

**Comment by phaticusthiccy** [comment]
REST APIs based on a http/s request. Many time it may won't work due connection or hosting problems.

**Comment by Oreki-san** [comment]
> REST APIs based on a http/s request. Many time it may won't work due connection or hosting problems.

Indeed it sometimes shows the url in the bot well nvm
I have 2 more command suggestions for asena
1. tagall/ping
2. ytv ( searches source video nd gives yt link )
Approval needed

**Pull request closed without merging**
