### PR TITLE
Admins? 😍

### PR DESCRIPTION
**Pull request by TOXIC-DEVIL**
**@phaticusthiccy I have made admins commands, only admins can use. If this is acceptable Please accept. If this is acceptable, Don't Forget to add Language Support for other Languages .. 😁 @phaticusthiccy**

### CODE REVIEW

**Comment by TOXIC-DEVIL** [comment]
Why this all are coming.. 😶😥

**Comment by TOXIC-DEVIL** [comment]
branch mistake happen....

**Comment by souravkl11** [comment]
@TOXIC-DEVIL Why did you closed this?

**Comment by TOXIC-DEVIL** [comment]
> @TOXIC-DEVIL Why did you closed this?

Some unknown error occured!

**Pull request closed without merging**
