### PR TITLE
New Command 🥳🥳 

### PR DESCRIPTION
**Pull request by TOXIC-DEVIL**
New Command 🥳🥳 Clear messages from the chat ✅️

### CODE REVIEW

**Comment by phaticusthiccy** [comment]
Thanks for precious pull request!

**Review by phaticusthiccy — APPROVED** [review]

**Comment by TOXIC-DEVIL** [comment]
> Thanks for precious pull request!

Welcome Bro 💖

**Comment by souravkl11** [comment]
@TOXIC-DEVIL  ❤

**Comment by TOXIC-DEVIL** [comment]
> @TOXIC-DEVIL ❤

😂💖💖

**Comment by souravkl11** [comment]
@TOXIC-DEVIL  Ith use cheyyumbol ban risk ille

**Comment by TOXIC-DEVIL** [comment]
> @TOXIC-DEVIL Ith use cheyyumbol ban risk ille
> Can I copy this plugin?

Illa! Sure! 💖

**Comment by TOXIC-DEVIL** [comment]
> @TOXIC-DEVIL Ith use cheyyumbol ban risk ille
> Can I copy this plugin?

Illa! Sure, You can use this plugin! 💖

**Pull request merged**
